baseline_params:
  colsample_bytree: 1.0
  early_stopping_rounds: 50
  enable_categorical: true
  eval_metric: aucpr
  learning_rate: 0.3
  max_delta_step: 0
  max_depth: 6
  min_child_weight: 1
  n_estimators: 500
  objective: binary:logistic
  random_state: 42
  reg_alpha: 0
  reg_lambda: 1
  subsample: 1.0
tuned_v1:
  colsample_bytree: 0.8
  early_stopping_rounds: 50
  enable_categorical: true
  eval_metric: aucpr
  learning_rate: 0.05
  max_delta_step: 1
  max_depth: 4
  min_child_weight: 5
  n_estimators: 500
  objective: binary:logistic
  random_state: 42
  reg_alpha: 0
  reg_lambda: 1
  subsample: 0.8
